name: Approaching Space
favicon: null
layout_spectrum: 0.2373
typography_spectrum: 0.26886
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#0a0a17'
    - '#27317c'
    - '#d7d7d8'
    - '#6a83a7'
    - '#9fb2ce'
  brandStrength: 0.25
  lightness: 0.625
  saturation: 0.3125
  rhythmicContrast: 0.5
purpose: []
